{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle-api",
    "version": "7.1.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "7.0"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-7.1.0-alpha01.jar",
          "url": "gradle-api-7.1.0-alpha01.jar",
          "size": 209477,
          "sha512": "02e7beeda5b32c92fa9d85ddba15b6a80462e6911161c5365fcd38f3a510e109a68c619fb0be0360f86851def6c2cca21725adcf1760a92704126b261c4c2b34",
          "sha256": "7cf29b943d5c8f550c67ae5d0b2d0a6b9450a9ad5470a95acc44c270d32958db",
          "sha1": "d27d5eedd4dc9dfffb01c60099e26212a0479a8d",
          "md5": "942a30bd3903c628b88b03e6a4f783ef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "7.1.0-alpha01"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "7.0"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-7.1.0-alpha01.jar",
          "url": "gradle-api-7.1.0-alpha01.jar",
          "size": 209477,
          "sha512": "02e7beeda5b32c92fa9d85ddba15b6a80462e6911161c5365fcd38f3a510e109a68c619fb0be0360f86851def6c2cca21725adcf1760a92704126b261c4c2b34",
          "sha256": "7cf29b943d5c8f550c67ae5d0b2d0a6b9450a9ad5470a95acc44c270d32958db",
          "sha1": "d27d5eedd4dc9dfffb01c60099e26212a0479a8d",
          "md5": "942a30bd3903c628b88b03e6a4f783ef"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-7.1.0-alpha01-javadoc.jar",
          "url": "gradle-api-7.1.0-alpha01-javadoc.jar",
          "size": 464931,
          "sha512": "76cb3334d9a7bd4636014f7e6511648b6eb611e2ec25acb968c3386c7d1dcfe8396f5bcf815802ccb562e25ba887531bc8aaa1beb91c6db67518bd0ddd2a4050",
          "sha256": "1eefe11bdcbac0ba3f56369eea9b79d271ee0cae9aa9fd61a915f240e5df2058",
          "sha1": "e0ebefc15924e5b2cf99c986bbf30c8007f2f86f",
          "md5": "7adfa9f65fe2f40e2041ba29e6b25842"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-7.1.0-alpha01-sources.jar",
          "url": "gradle-api-7.1.0-alpha01-sources.jar",
          "size": 210693,
          "sha512": "1113ad15bb9a21d1aaa71f584c8907101e829105e6014d9fb1fa02923243cc56d4cdc834c37b3bc4af9cc9d3693505781e15b5687d6e6e222b9635cb0a0fa56a",
          "sha256": "525bea4570c7863710403dc97a28b33fdc5bdc4a22243121c35132be88dac022",
          "sha1": "ec3d8fd383b5a898c466e6cdac2b5fa2c47c74cd",
          "md5": "080ef15626a42a104bafdc0e8b9b6349"
        }
      ]
    }
  ]
}
